mc_admin_messages:
    path: /
    defaults: 
        _controller: MCMessagesBundle:Messages:home

mc_admin_messages_received:
    path: /inbox/page{page}/
    defaults: 
        _controller: MCMessagesBundle:Messages:receivedMessages
        page: 1

mc_admin_messages_received_preview:
    path: /inbox/page{page}/{message_id}/
    defaults: 
        _controller: MCMessagesBundle:Messages:receivedMessagesWithPreview
        page: 1

mc_admin_messages_sent:
    path: /sent/page{page}/
    defaults:
        _controller: MCMessagesBundle:Messages:sentMessages
        page: 1

mc_admin_messages_sent_preview:
    path: /sent/page{page}/{message_id}/
    defaults:
        _controller: MCMessagesBundle:Messages:sentMessagesWithPreview
        page: 1

mc_admin_messages_draft:
    path: /draft/page{page}/
    defaults:
        _controller: MCMessagesBundle:Messages:draftMessages
        page: 1

mc_admin_messages_draft_preview:
    path: /draft/page{page}/{message_id}/
    defaults:
        _controller: MCMessagesBundle:Messages:draftMessagesWithPreview
        page: 1

mc_admin_messages_unread:
    path: /inbox-new/
    defaults:
        _controller: MCMessagesBundle:Messages:unreadMessages

mc_admin_messages_unread_preview:
    path: /inbox-new/{message_id}/
    defaults:
        _controller: MCMessagesBundle:Messages:unreadMessagesWithPreview

mc_admin_messages_new:
    path: /new/
    defaults:
        _controller: MCMessagesBundle:Messages:new

mc_admin_messages_new_preview:
    path: /new/{message_id}/
    defaults:
        _controller: MCMessagesBundle:Messages:newWithPreview

mc_admin_messages_new_to:
    path: /new/{to}/
    defaults:
        _controller: MCMessagesBundle:Messages:newTo

mc_admin_messages_reply:
    path: /new/{message_id}/
    defaults:
        _controller: MCMessagesBundle:Messages:reply
