services:
#    mesclics_messages.example:
#        class: MesClics\MessagesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    mesclics_messages.message_reader:
        class: MesClics\MessagesBundle\MessageReader\MessageReader
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"

    mesclics_messages.message_read_listener:
        class: MesClics\MessagesBundle\Events\EventListeners\MessageReadListener
        arguments:
            - "@mesclics_messages.message_reader"
        tags:
            - { name: kernel.event_listener, event: mesclics_messages.read_message, method: process }
    
    mesclics_messages.form_manager.new:
        class: MesClics\MessagesBundle\Form\FormManager\MessageFormManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
            - "@session"
    
    mesclics_messages.form_manager.user:
        class: MesClics\MessagesBundle\Form\FormManager\UserMessageFormManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
            - "@session"

    mesclics_messages.counter:
        class: MesClics\MessagesBundle\MessagesCounter\MessagesCounter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"

    mesclics_messages.twig.counter:
        class: MesClics\MessagesBundle\Twig\MessagesCounterExtension
        arguments:
            - "@mesclics_messages.counter"
        tags:
            - { name: twig.extension }
